### PR TITLE
Updated rounded corners.

### PR DESCRIPTION
**Pull request by ghost**
Updated the function to match suckless format, and only draw arcs over necessary degrees. Also did some fiddling to see what function calls were actually necessary.

Fixed issues with client position after floating then retiling, and clients now unround and reround upon fullscreen toggling.

Sorry about the messy patch file and its incongruency with yours - I got this working on my patched dwm (i.e. stext variable, slightly offset function locations). Not sure if `patch` will sort it all out properly, but the content is here!

### CODE REVIEW

**Comment by kopr12** [comment]
@gitluin working great here, don't know much about X11 drawing but what do you think about drawing rounded borders for focused windows ?
Can you add that please?
Thanks.

**Comment by mitchweaver** [comment]
I don't use rounded corners anymore but this sounds like a good idea for a fork.

**Comment by kopr12** [comment]
Yeah I'm on and off with it as well, main problem was no border, I think with this PR rounded corners are looking better than with your solution IMHO

**Comment by kopr12** [comment]
I managed to solve that problem.

**Comment by ghost** [comment]
Based on what mitch said, I figured I'd package it as a patch for the base dwm and submit it that way, so that's my plan when I get the chance. I'd also be happy to update the one for mitch's dwm and update this PR, especially with one that doesn't conflict and just requires a button push to integrate.

I haven't taken a look at making sure borders are drawn, but I think just swapping in `c->bw` in place of some `0`s that I stuck in there would do it?

**Comment by kopr12** [comment]
I took solution from bspwm, it's actually not merged.
Anyway, it works great.
https://github.com/dylanaraps/bspwm/commit/e8d8f924d7902a6bdc06b515bd43424f8b889474.patch

**Comment by ghost** [comment]
I made `rounded-corners.patch` for the base version of dwm. I know this doesn't apply as much to your version, mitch, particularly since you don't use rounded corners, but I figured I would mention it here and close this up. You can find it [here](https://github.com/gitluin/dwm-patches), and if I can figure out how to get clients like chromium to play nice, then I'll send it off to the suckless folks.

**Comment by kopr12** [comment]
@gitluin recently I've uploaded patch for rounded corners [here](https://github.com/kajzersoze/dwm/blob/master/x11-wm/dwm/files/dwm-patches-6.2.diff#L864) , I don't use chromium so I don't know are there any problems with it but it works fine with everything else I tried.

**Comment by ghost** [comment]
@kajzersoze Nice! Cool to see the bspwm code retooled successfully. I think both versions existing is a good thing, since your version is xcb and my implementation is Xlib. While in some sense that doesn't matter (my understanding is Xlib has been reimplemented as a layer on top of xcb), I'm sure there are people who will want as few headers as possible.

**Comment by kopr12** [comment]
Yeah that's a downside (xcb) but that's the only version I was able to get borders with rounded corners.
I'm sure that the same thing could be done with Xlib but I just can't grasp X11 drawing stuff, too complicated for me :D

**Pull request closed without merging**
